#!/usr/bin/env node
/**
 * Build the JSON the Worker bundles for local development and as a production
 * fallback when no D1 binding is attached (the procurement table is always bundled).
 *
 * Outputs (committed, regenerated by `npm run build-data`):
 *   src/data/procurement-stats.json  the same compact table @deltakura/mcp ships
 *   src/data/nta-dev.json            daily change counts, from the published
 *                                    summary alone
 *
 * And one file that `npm run build-data` deliberately does NOT touch:
 *   src/data/nta-sample.json         a fixed corporate-record sample, refreshed
 *                                    only by `--refresh-sample` on a machine
 *                                    that holds the private store (see below)
 *
 * Inputs, in this monorepo:
 *   ../data/published/pportal/procurement-stats.json  the compact table, built
 *       by ../mcp/scripts/build-data.mjs. Copied, never rebuilt here, so the MCP
 *       server and the Worker cannot drift into answering one question two ways.
 *   ../data/published/nta/summary.json                daily corporate-registry
 *       change counts. Its `records` field is the DEDUPLICATED count and is the
 *       single authority for every public surface.
 *   $DELTAKURA_DATA_DIR (default ../../data)          the private record store,
 *       used only to fill the bundled development sample. Absent in CI, in which
 *       case the counts still come out right and the sample is empty.
 *
 * Usage:
 *   node scripts/build-data.mjs [--check]
 *   node scripts/build-data.mjs --refresh-sample [--data-dir <dir>] [--sample <n>]
 *
 * DETERMINISM. A normal run reads only files inside this
 * repository and writes no timestamp, so the same checkout always produces the
 * same bytes and CI can assert `npm run build-data && git diff --exit-code`.
 * Provenance is carried by `source_version`, the SHA-256 of the published
 * summary this bundle was derived from.
 *
 * THE SAMPLE. `src/data/nta-sample.json` is what `wrangler dev --local` answers
 * corporate lookups from. It cannot be derived from `data/published/`, which
 * holds counts and no records, so it is a FIXED file, committed once and
 * regenerated only on request. Its rule, so that anyone holding the same
 * private store reproduces it byte for byte:
 *
 *   take every row of the normalized layer whose corporate number passes the
 *   check digit and whose 法人種別 is a registered corporation or public body;
 *   sort by (file_date, corporate_number, sequence_number); keep the first
 *   `--sample` (default 1500); keep only the SAMPLE_FIELDS columns, in order.
 *
 * Nothing here reaches the network and nothing outside this package is written.
 */
import { createReadStream, existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { createGunzip } from 'node:zlib';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { pathToFileURL } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(HERE, '..');
const REPO_ROOT = resolve(PKG_ROOT, '..');
const MCP_ROOT = join(REPO_ROOT, 'mcp');
const PUBLISHED = join(REPO_ROOT, 'data', 'published');
const NTA_SUMMARY = join(PUBLISHED, 'nta', 'summary.json');
const OUT_DIR = join(PKG_ROOT, 'src', 'data');
const SAMPLE_PATH = join(OUT_DIR, 'nta-sample.json');
const DEFAULT_SAMPLE = 1500;
const SAMPLE_RULE =
  'Fixed development sample. Rows of the private normalized layer with a ' +
  'checksum-valid corporate number and a corporate/public-body 法人種別, sorted ' +
  'by (file_date, corporate_number, sequence_number), first N kept, restricted ' +
  'to the SAMPLE_FIELDS allowlist. Regenerated only by ' +
  '`node scripts/build-data.mjs --refresh-sample`, never by a normal build, so ' +
  'the committed bundles stay reproducible without the private store.'

function arg(name, fallback) {
  const i = process.argv.indexOf(name);
  return i === -1 ? fallback : process.argv[i + 1];
}

/**
 * The PRIVATE record store, never the published directory. Defaults to `../data`
 * relative to the repository root, which is where the collectors write.
 */
function resolveDataDir() {
  const candidates = [
    arg('--data-dir'),
    process.env.DELTAKURA_DATA_DIR,
    resolve(REPO_ROOT, '..', 'data')
  ].filter(Boolean);
  for (const c of candidates) {
    if (existsSync(join(c, 'nta')) || existsSync(join(c, 'normalized'))) return c;
  }
  return undefined;
}

function ntaRoot(dataDir) {
  for (const c of [join(dataDir, 'nta'), dataDir]) {
    if (existsSync(join(c, 'normalized')) || existsSync(join(c, 'manifest.csv'))) return c;
  }
  return undefined;
}

/* ------------------------------------------------------------------ CSV --- */

async function streamCsvRecords(path, visit) {
  const source = createReadStream(path);
  const stream = path.endsWith('.gz') ? source.pipe(createGunzip()) : source;
  stream.setEncoding('utf8');
  let header;
  let row = [];
  let field = '';
  let quoted = false;
  let quoteSeen = false;
  let stopped = false;

  const emit = () => {
    row.push(field);
    field = '';
    const current = row;
    row = [];
    if (stopped) return;
    if (!header) {
      header = current.map((h) => h.replace(/^﻿/, '').trim());
      return;
    }
    if (current.length === 1 && current[0] === '') return;
    const rec = {};
    for (let i = 0; i < header.length; i++) rec[header[i]] = current[i] ?? '';
    if (visit(rec) === 'stop') stopped = true;
  };

  for await (const chunk of stream) {
    for (let i = 0; i < chunk.length; i++) {
      const c = chunk[i];
      if (quoted) {
        if (quoteSeen) {
          quoteSeen = false;
          if (c === '"') { field += '"'; continue; }
          quoted = false;
        } else if (c === '"') { quoteSeen = true; continue; }
        else { field += c; continue; }
      }
      if (c === '"') { quoted = true; continue; }
      if (c === ',') { row.push(field); field = ''; continue; }
      if (c === '\r') continue;
      if (c === '\n') { emit(); continue; }
      field += c;
    }
    if (stopped) break;
  }
  source.destroy();
  if (!stopped && (field !== '' || row.length)) emit();
}

/* --------------------------------------------------------- procurement --- */

async function buildProcurement() {
  // Copy, in preference order: the published artefact, then the MCP package's
  // own copy. Both are written from the same bytes by ../mcp/scripts/build-data.mjs.
  for (const shipped of [
    join(PUBLISHED, 'pportal', 'procurement-stats.json'),
    join(MCP_ROOT, 'data', 'procurement-stats.json')
  ]) {
    if (existsSync(shipped)) return readFileSync(shipped, 'utf8');
  }

  const builder = join(MCP_ROOT, 'scripts', 'build-data.mjs');
  if (!existsSync(builder)) {
    throw new Error(
      `no built procurement table under ${PUBLISHED} or ${MCP_ROOT}, and ${builder} ` +
        'is missing. Run `npm run build-data` in ../mcp first.'
    );
  }
  const { buildDataset } = await import(pathToFileURL(builder).href);
  const csv = [
    process.env.DELTAKURA_STATS_CSV,
    join(PUBLISHED, 'pportal', 'stats_v0.csv'),
    process.env.DELTAKURA_DATA_DIR ? join(process.env.DELTAKURA_DATA_DIR, 'pportal', 'stats_v0.csv') : undefined
  ].filter(Boolean).find((p) => existsSync(p));
  if (!csv) throw new Error('stats_v0.csv not found; set DELTAKURA_STATS_CSV or run ../mcp build-data');
  return JSON.stringify(buildDataset(readFileSync(csv, 'utf8')));
}

/* ----------------------------------------------------------------- NTA --- */

/** Mirrors the allowlist in mcp/src/query/nta.ts: nothing else is ever written out. */
const SAMPLE_FIELDS = [
  'corporate_number', 'name', 'kind_code', 'prefecture', 'prefecture_code', 'city',
  'process_code', 'correct_flag', 'update_date', 'change_date', 'sequence_number',
  'close_date', 'close_cause', 'successor_corporate_number', 'assignment_date',
  'latest_flag', 'file_date'
];
const PERSONAL_FIELD_PATTERN =
  /担当|氏名|代表者|代表取締役|役員|連絡先|電話|メール|個人|生年月日|e-?mail|phone|telephone|contact_|person_|birth/i;

const NTA_ATTRIBUTION =
  '出典：国税庁法人番号公表サイト（国税庁）（https://www.houjin-bangou.nta.go.jp/download/sabun/）';
const NTA_LICENSE =
  '公共データ利用規約(第1.0版) — commercial reuse and redistribution permitted with attribution; modifications must be declared.';
const NTA_SOURCE_URL = 'https://www.houjin-bangou.nta.go.jp/download/sabun/';

/** 法人種別 that are registered corporations or public bodies (KIND_CODES in mcp/src/query/nta.ts). */
const CORPORATE_KIND_CODES = new Set(['101', '201', '301', '302', '303', '304', '305', '399']);

/** Deterministic stand-in for a build timestamp: the input's own content hash. */
function sourceVersion(text) {
  return 'sha256-' + createHash('sha256').update(text, 'utf8').digest('hex').slice(0, 16);
}

function emptyNtaDev(reason) {
  return {
    schema: 1,
    source_version: 'sha256-' + '0'.repeat(16),
    note: reason,
    license: NTA_LICENSE,
    attribution: NTA_ATTRIBUTION,
    source_url: NTA_SOURCE_URL,
    coverage: { from: null, to: null, days_with_data: 0 },
    daily: {},
    daily_by_kind: {}
  };
}

function buildNta() {
  if (!existsSync(NTA_SUMMARY)) {
    return emptyNtaDev(
      'No published NTA summary at data/published/nta/summary.json. Run ' +
        '`python crawlers/nta_diff/publish_summary.py` first.'
    );
  }
  const summaryText = readFileSync(NTA_SUMMARY, 'utf8');
  const summary = JSON.parse(summaryText);
  const days = summary.days ?? {};

  // The published summary is the authority for every count. `records` there is
  // the DEDUPLICATED figure; `records_raw` is the publisher's own
  // row count and is carried only so the difference stays explained. The Worker
  // publishes the deduplicated number, exactly like the site and the feed.
  const daily = {};
  const dailyByKind = {};
  for (const [date, entry] of Object.entries(days)) {
    daily[date] = Number(entry.records ?? 0) || 0;
    const codes = entry.process_codes ?? {};
    if (Object.keys(codes).length) dailyByKind[date] = codes;
  }

  const dates = Object.keys(daily).sort();

  return {
    schema: 1,
    source_version: summary.source_version ?? sourceVersion(summaryText),
    note:
      'Daily counts come from data/published/nta/summary.json and are deduplicated: ' +
      'they are the same numbers the site, the RSS feed and the MCP ' +
      'server report. This file is built from that summary alone and carries no ' +
      'records; the bundled development sample lives in nta-sample.json. Production ' +
      'serves corporate lookups from D1.',
    license: summary.license ?? NTA_LICENSE,
    attribution: summary.attribution ?? NTA_ATTRIBUTION,
    source_url: summary.source_url ?? NTA_SOURCE_URL,
    modification_notice: summary.modification_notice,
    count_rule: summary.count_rule,
    coverage: {
      from: dates[0] ?? null,
      to: dates.at(-1) ?? null,
      days_with_data: dates.length,
      records: Number(summary.coverage?.records ?? 0) || 0,
      records_raw: Number(summary.coverage?.records_raw ?? 0) || 0
    },
    daily,
    daily_by_kind: dailyByKind
  };
}

/**
 * Build the FIXED development sample from the PRIVATE record store, by the rule
 * documented at the top of this file. Deterministic: the same store always
 * yields the same records in the same order, so `--refresh-sample` on two
 * machines holding the same archive writes the same bytes.
 *
 * Returns undefined when no private store is present, which is the CI case and
 * is not an error - a normal build never calls this.
 */
async function buildSample(dataDir, sampleSize) {
  if (!dataDir || sampleSize <= 0) return undefined;
  const root = ntaRoot(dataDir);
  if (!root) return undefined;
  const normalizedDir = join(root, 'normalized');
  if (!existsSync(normalizedDir)) return undefined;
  const files = readdirSync(normalizedDir)
    .filter((f) => f.endsWith('.csv.gz') || f.endsWith('.csv'))
    .sort();

  const rows = [];
  let checkedHeader = false;
  for (const file of files) {
    await streamCsvRecords(join(normalizedDir, file), (rec) => {
      if (!checkedHeader) {
        for (const h of Object.keys(rec)) {
          if (PERSONAL_FIELD_PATTERN.test(h)) {
            throw new Error(`normalized column "${h}" matches the personal-data pattern`);
          }
        }
        checkedHeader = true;
      }
      if (rec.corporate_number_valid && rec.corporate_number_valid !== 'Y') return;
      // Defence in depth. The server masks a token-free name on a non-corporate
      // corporate kind at read time; this sample is committed to a public
      // repository, so such a record is not put at rest in it at all.
      if (!CORPORATE_KIND_CODES.has(rec.kind_code)) return;
      const out = {};
      for (const f of SAMPLE_FIELDS) if (rec[f]) out[f] = rec[f];
      rows.push(out);
    });
  }

  // The order is part of the rule, not an artefact of the file layout.
  rows.sort(
    (a, b) =>
      (a.file_date ?? '').localeCompare(b.file_date ?? '') ||
      (a.corporate_number ?? '').localeCompare(b.corporate_number ?? '') ||
      (a.sequence_number ?? '').localeCompare(b.sequence_number ?? '')
  );
  const records = rows.slice(0, sampleSize);

  return {
    schema: 1,
    note:
      'Fixed sample of the Bet-C corporate-registry diff, bundled so that ' +
      '`wrangler dev --local` and the test suite can answer corporate lookups ' +
      'offline. Registered corporations and public bodies only; corporate numbers ' +
      'are not issued to sole proprietors and no individual appears here.',
    rule: SAMPLE_RULE,
    license: NTA_LICENSE,
    attribution: NTA_ATTRIBUTION,
    source_url: NTA_SOURCE_URL,
    fields: SAMPLE_FIELDS,
    sample_size: records.length,
    sample_is_partial: true,
    records
  };
}

/* ---------------------------------------------------------------- main --- */

async function refreshSample() {
  const sampleSize = Number(arg('--sample', String(DEFAULT_SAMPLE))) || DEFAULT_SAMPLE;
  const dataDir = resolveDataDir();
  const sample = await buildSample(dataDir, sampleSize);
  if (!sample) {
    throw new Error(
      '--refresh-sample needs the private record store. Set DELTAKURA_DATA_DIR or ' +
        'pass --data-dir; there is nothing to sample from inside this repository.'
    );
  }
  mkdirSync(OUT_DIR, { recursive: true });
  const json = JSON.stringify(sample);
  writeFileSync(SAMPLE_PATH, json, 'utf8');
  console.log(
    `wrote ${SAMPLE_PATH}\n  ${sample.sample_size} records, ` +
      `${(Buffer.byteLength(json) / 1024).toFixed(0)} KB\n` +
      '  Fixed file: `npm run build-data` never rewrites it, so a rebuild is a ' +
      'deliberate commit of its own.'
  );
}

async function main() {
  if (process.argv.includes('--refresh-sample')) {
    await refreshSample();
    return;
  }

  const procurement = await buildProcurement();
  const nta = buildNta();
  const ntaJson = JSON.stringify(nta);

  if (process.argv.includes('--check')) {
    for (const [name, wanted] of [
      ['procurement-stats.json', procurement],
      ['nta-dev.json', ntaJson]
    ]) {
      const existing = join(OUT_DIR, name);
      if (!existsSync(existing)) throw new Error(`--check: ${existing} does not exist`);
      // Byte-for-byte: neither payload carries anything a second build could
      // legitimately change.
      if (readFileSync(existing, 'utf8') !== wanted) {
        throw new Error(`--check: committed ${name} differs from a fresh build`);
      }
    }
    if (!existsSync(SAMPLE_PATH)) throw new Error(`--check: ${SAMPLE_PATH} does not exist`);
    console.log('ok: bundled procurement table and NTA counts match a fresh build');
    return;
  }

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(join(OUT_DIR, 'procurement-stats.json'), procurement, 'utf8');
  writeFileSync(join(OUT_DIR, 'nta-dev.json'), ntaJson, 'utf8');

  const total = Buffer.byteLength(procurement) + Buffer.byteLength(ntaJson);
  console.log(
    `wrote ${OUT_DIR}\n  procurement-stats.json: ${(Buffer.byteLength(procurement) / 1024).toFixed(0)} KB` +
      `\n  nta-dev.json: ${(Buffer.byteLength(ntaJson) / 1024).toFixed(0)} KB ` +
      `(${nta.coverage.days_with_data} days of counts, no records)` +
      `\n  bundled total: ${(total / 1024 / 1024).toFixed(2)} MB` +
      '\n  nta-sample.json is fixed and was not touched (--refresh-sample rebuilds it).'
  );
}

main().catch((err) => {
  console.error(String(err instanceof Error ? err.message : err));
  process.exit(1);
});
