#!/usr/bin/env node
/**
 * Write the SQL that loads D1 `signals` with exactly what the Worker bundle
 * already serves, and nothing more:
 *
 *   nta_daily, nta_daily_kind   from src/data/nta-dev.json, which build-data
 *                               derives from data/published/nta/summary.json
 *                               (deduplicated counts; the single authority)
 *   nta_change                  from src/data/nta-sample.json, the fixed
 *                               record sample already committed to this repo
 *   load_log                    one row per day, so coverage is inspectable
 *
 * No private record store is read, so D1 never holds anything that is not
 * already public in the repository. That is also why production sets
 * CORPORATE_RECORDS = "sample": lookups answer complete=false.
 *
 * The script only writes a file. Loading it is an operator action:
 *
 *   npm run build-data
 *   node scripts/d1-seed.mjs                      # -> .wrangler/d1-seed.sql
 *   npx wrangler d1 execute signals --remote --env production --file .wrangler/d1-seed.sql
 *
 * The file replaces the tables' contents, so re-running it after a data
 * rebuild is safe. Free-tier cost: about 1,500 x 3 (row + 2 indexes) plus a
 * few hundred count rows, i.e. roughly 5,000 of the 100,000 daily D1 row writes.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const API = join(HERE, '..');
const OUT = process.argv[2] ?? join(API, '.wrangler', 'd1-seed.sql');

const nta = JSON.parse(readFileSync(join(API, 'src', 'data', 'nta-dev.json'), 'utf8'));
const sample = JSON.parse(readFileSync(join(API, 'src', 'data', 'nta-sample.json'), 'utf8'));

const CHANGE_COLUMNS = [
  'corporate_number', 'change_date', 'sequence_number', 'correct_flag', 'process_code', 'update_date',
  'file_date', 'name', 'kind_code', 'prefecture', 'prefecture_code', 'city', 'close_date', 'close_cause',
  'successor_corporate_number', 'assignment_date', 'latest_flag'
];
const INTEGER_COLUMNS = new Set(['sequence_number', 'correct_flag', 'latest_flag']);

function lit(value, integer = false) {
  if (value === undefined || value === null || value === '') return integer ? '0' : 'NULL';
  if (integer) {
    const n = Number(value);
    if (!Number.isInteger(n)) throw new Error(`not an integer: ${value}`);
    return String(n);
  }
  return `'${String(value).replace(/'/g, "''")}'`;
}

function chunks(rows, size) {
  const out = [];
  for (let i = 0; i < rows.length; i += size) out.push(rows.slice(i, i + size));
  return out;
}

const sql = [
  '-- Generated by api/scripts/d1-seed.mjs. Do not edit; do not commit.',
  `-- counts: ${nta.source_version}; sample: ${sample.sample_size} records`,
  'DELETE FROM nta_change;',
  'DELETE FROM nta_daily;',
  'DELETE FROM nta_daily_kind;',
  "DELETE FROM load_log WHERE source_id IN ('nta_diff_summary', 'nta_sample');"
];

const dates = Object.keys(nta.daily).sort();
for (const part of chunks(dates, 50)) {
  sql.push(
    'INSERT INTO nta_daily (file_date, changes, status) VALUES ' +
      part.map((d) => `(${lit(d)}, ${lit(nta.daily[d], true)}, 'ok')`).join(', ') +
      ';'
  );
}

const kindRows = [];
for (const d of Object.keys(nta.daily_by_kind).sort()) {
  for (const [code, n] of Object.entries(nta.daily_by_kind[d]).sort()) kindRows.push([d, code, n]);
}
for (const part of chunks(kindRows, 50)) {
  sql.push(
    'INSERT INTO nta_daily_kind (file_date, process_code, changes) VALUES ' +
      part.map(([d, c, n]) => `(${lit(d)}, ${lit(c)}, ${lit(n, true)})`).join(', ') +
      ';'
  );
}

for (const part of chunks(sample.records, 25)) {
  sql.push(
    `INSERT OR REPLACE INTO nta_change (${CHANGE_COLUMNS.join(', ')}) VALUES ` +
      part.map((r) => '(' + CHANGE_COLUMNS.map((c) => lit(r[c], INTEGER_COLUMNS.has(c))).join(', ') + ')').join(', ') +
      ';'
  );
}

const loadedAt = new Date().toISOString();
for (const part of chunks(dates, 50)) {
  sql.push(
    'INSERT OR REPLACE INTO load_log (loaded_at, source_id, file_date, rows_loaded) VALUES ' +
      part.map((d) => `(${lit(loadedAt)}, 'nta_diff_summary', ${lit(d)}, ${lit(nta.daily[d], true)})`).join(', ') +
      ';'
  );
}
sql.push(
  `INSERT OR REPLACE INTO load_log (loaded_at, source_id, file_date, rows_loaded) VALUES ` +
    `(${lit(loadedAt)}, 'nta_sample', 'fixed', ${sample.records.length});`
);

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, sql.join('\n') + '\n', 'utf8');
console.log(
  `wrote ${OUT}\n  nta_daily ${dates.length} rows, nta_daily_kind ${kindRows.length} rows, ` +
    `nta_change ${sample.records.length} rows (sample), load_log ${dates.length + 1} rows`
);
